export const BRAND = {
  name: "Furnshin",
  tagline: "Spaces Designed for Luxury",
  taglineAlt: "Designing Spaces That Speaks",
  uvp: "Furnshin delivers end to end interior and furnishing solutions for homes and commercial spaces in Jaipur through 30 years of craftsmanship, design-led execution, and finishing quality that transforms every space into something built to last.",
  founded: 1996,
  yearsInBusiness: "30+",
  projectsCompleted: "50+",
  reach: "Pan-India",
  email: "Furnshin@gmail.com",
  phone: "+91 9828101833",
  whatsapp: "919828101833",
  address: {
    street: "Petunia 201, Manglam Aananda, Sanganer",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    pincode: "302029",
    full: "Petunia 201, Manglam Aananda, Sanganer, Jaipur, Rajasthan 302029",
  },
  geo: { lat: 26.9124, lng: 75.7873 },
  website: "https://furnshin.com",
  ga4: "G-01FKMZ7BQ1",
  social: {
    instagram: "https://www.instagram.com/furnshin.interiors/",
    youtube: "https://www.youtube.com/@furnshin.interiors",
    twitter: "https://x.com/furnshin",
    facebook: "https://facebook.com/Furnshin",
  },
  colors: {
    espresso: "#2C1810",
    sandGold: "#C9A96E",
    secondaryBrown: "#5C3D2E",
    cream: "#FAF7F4",
    beige: "#F0EBE3",
    textDark: "#1C110A",
    taupe: "#D4C4B5",
  },
  services: [
    {
      id: "interior-decor",
      name: "Interior Decoration",
      slug: "interior-decoration",
      description: "Complete interior design and decor solutions for homes and commercial spaces.",
      icon: "Home",
    },
    {
      id: "glass-works",
      name: "Glass Works",
      slug: "glass-works",
      description: "Decorative glass partitions, shower enclosures, glass doors, and custom glass installations.",
      icon: "Layers",
    },
    {
      id: "custom-furniture",
      name: "Custom Furniture",
      slug: "custom-furniture",
      description: "Bespoke modular kitchens, wardrobes, beds, and custom wood furniture built to specification.",
      icon: "Sofa",
    },
    {
      id: "aluminum-solutions",
      name: "Aluminum Solutions",
      slug: "aluminum-solutions",
      description: "Aluminum windows, doors, facades, and structural aluminum fabrication.",
      icon: "Square",
    },
    {
      id: "iron-metal-works",
      name: "Iron & Metal Works",
      slug: "iron-metal-works",
      description: "Custom iron gates, MS railings, safety grills, and decorative metal fabrication.",
      icon: "Wrench",
    },
    {
      id: "floor-decor",
      name: "Floor Decor",
      slug: "floor-decor",
      description: "Premium flooring solutions including tiles, marble, and wood-effect finishes.",
      icon: "Grid",
    },
  ],
} as const;

export const SEO_DEFAULTS = {
  titleTemplate: "%s | Furnshin",
  defaultTitle: "Furnshin — Spaces Designed for Luxury | Interior & Furnishing Solutions Jaipur",
  description:
    "Furnshin delivers design-led interior and furnishing solutions for homes and commercial spaces in Jaipur. 30 years of craftsmanship. Glass work, custom furniture, aluminum, iron fabrication. Call +91 9828101833.",
  canonical: "https://furnshin.com",
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: "https://furnshin.com",
    siteName: "Furnshin",
    images: [
      {
        url: "https://furnshin.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Furnshin — Interior & Furnishing Solutions Jaipur",
      },
    ],
  },
  twitter: {
    handle: "@furnshin",
    site: "@furnshin",
    cardType: "summary_large_image",
  },
};
