export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  tags: string[];
  publishedAt: string;
  readTime: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "complete-home-interior-guide-jaipur-2026",
    title: "Complete Home Interior Guide for Jaipur Homeowners 2026",
    excerpt: "Everything a Jaipur homeowner needs to know before starting an interior project — budgeting, materials, timelines, and finding the right execution partner.",
    category: "Interior Design",
    tags: ["home interior", "jaipur", "interior guide", "2026"],
    publishedAt: "2026-03-01",
    readTime: "8 min read",
    metaTitle: "Complete Home Interior Guide for Jaipur Homeowners 2026 | Furnshin",
    metaDescription: "Planning your home interior in Jaipur? This complete 2026 guide covers budgeting, material selection, timelines, and how to choose the right furnishing partner.",
    keywords: ["home interior jaipur", "interior design guide jaipur", "home renovation jaipur 2026"],
  },
  {
    slug: "how-to-choose-modular-wardrobe-jaipur",
    title: "How to Choose the Right Modular Wardrobe for Your Bedroom",
    excerpt: "Material, finish, layout, and pricing — the complete decision guide for modular wardrobes in Jaipur homes.",
    category: "Furniture",
    tags: ["modular wardrobe", "custom furniture", "bedroom interior", "jaipur"],
    publishedAt: "2026-03-05",
    readTime: "6 min read",
    metaTitle: "How to Choose the Right Modular Wardrobe for Your Bedroom | Furnshin Jaipur",
    metaDescription: "Material, finish, layout, and sizing — the complete guide to choosing a modular wardrobe for your Jaipur bedroom. Custom furniture by Furnshin.",
    keywords: ["modular wardrobe jaipur", "custom wardrobe jaipur", "bedroom furniture jaipur"],
  },
  {
    slug: "glass-partition-vs-wall-office-jaipur",
    title: "Glass Partition vs Wall: Which is Better for Office Spaces in Jaipur?",
    excerpt: "Cost, acoustics, light, and aesthetics — an honest comparison of glass partitions versus traditional walls for Jaipur offices.",
    category: "Glass Works",
    tags: ["glass partition", "office interior", "jaipur", "commercial space"],
    publishedAt: "2026-03-10",
    readTime: "5 min read",
    metaTitle: "Glass Partition vs Wall for Office Spaces in Jaipur | Furnshin",
    metaDescription: "Glass partition or traditional wall for your Jaipur office? Compare cost, acoustics, light transmission, and design appeal. Expert advice from Furnshin.",
    keywords: ["glass partition office jaipur", "glass partition vs wall", "office interior jaipur"],
  },
  {
    slug: "interior-design-trends-jaipur-2026",
    title: "Top 10 Interior Design Trends in Jaipur for 2026",
    excerpt: "What Jaipur homeowners are choosing in 2026 — warm earth palettes, multi-functional furniture, and natural material preferences.",
    category: "Interior Design",
    tags: ["interior trends", "jaipur", "2026", "home design"],
    publishedAt: "2026-03-15",
    readTime: "7 min read",
    metaTitle: "Top 10 Interior Design Trends in Jaipur for 2026 | Furnshin",
    metaDescription: "Discover the top interior design trends in Jaipur for 2026. Warm earth tones to space-efficient furniture — what Jaipur homeowners are choosing this year.",
    keywords: ["interior design trends jaipur 2026", "home design trends 2026", "interior trends rajasthan"],
  },
  {
    slug: "custom-furniture-vs-ready-made-jaipur",
    title: "Custom Furniture vs Ready-Made: What Jaipur Homeowners Actually Prefer",
    excerpt: "An honest comparison of custom-built versus ready-made furniture — cost, timeline, quality, and which is right for your situation.",
    category: "Furniture",
    tags: ["custom furniture", "ready-made furniture", "jaipur", "home interior"],
    publishedAt: "2026-03-18",
    readTime: "6 min read",
    metaTitle: "Custom Furniture vs Ready-Made: What Jaipur Homeowners Prefer | Furnshin",
    metaDescription: "Custom furniture or ready-made for your Jaipur home? Compare cost, quality, fit, and timeline. Honest advice from Furnshin.",
    keywords: ["custom furniture jaipur", "ready made furniture jaipur", "furniture comparison jaipur"],
  },
  {
    slug: "aluminum-windows-jaipur-rajasthan-climate",
    title: "Why Aluminum Windows Are the Smart Choice for Jaipur's Climate",
    excerpt: "Heat, dust, and monsoon — why aluminum outperforms wood and UPVC in Rajasthan's climate, and what to look for when buying.",
    category: "Aluminum Solutions",
    tags: ["aluminum windows", "jaipur", "rajasthan", "window solutions"],
    publishedAt: "2026-03-20",
    readTime: "5 min read",
    metaTitle: "Why Aluminum Windows Are Best for Jaipur's Climate | Furnshin",
    metaDescription: "Aluminum, UPVC, or wood windows for your Jaipur home? Understand how each material performs in Rajasthan's climate.",
    keywords: ["aluminum windows jaipur", "aluminum doors jaipur", "window solutions jaipur"],
  },
  {
    slug: "living-room-transformation-mansarovar-jaipur",
    title: "Living Room Transformation: Before & After in Mansarovar, Jaipur",
    excerpt: "How we transformed a bare 400 sq ft living room in Mansarovar into a warm, functional family space in 14 days.",
    category: "Project Showcase",
    tags: ["before after", "living room", "mansarovar", "jaipur project"],
    publishedAt: "2026-03-22",
    readTime: "4 min read",
    metaTitle: "Living Room Transformation Before After in Mansarovar Jaipur | Furnshin",
    metaDescription: "A 400 sq ft living room transformation in Mansarovar, Jaipur. False ceiling, flooring, TV unit, and full decor — 14 days from start to handover.",
    keywords: ["living room interior mansarovar jaipur", "home interior jaipur", "living room transformation jaipur"],
  },
  {
    slug: "iron-gate-designs-jaipur-homes",
    title: "Iron Gate Designs That Elevate Jaipur Home Exteriors",
    excerpt: "Design options, material choices, and what to specify when commissioning a custom iron gate in Jaipur.",
    category: "Iron & Metal Works",
    tags: ["iron gate", "metal fabrication", "jaipur exterior", "home exterior"],
    publishedAt: "2026-03-24",
    readTime: "5 min read",
    metaTitle: "Iron Gate Designs for Jaipur Homes | Furnshin",
    metaDescription: "Custom iron gate designs for Jaipur homes. Design options, material specifications, and pricing. By Furnshin — 30 years of metal fabrication in Jaipur.",
    keywords: ["iron gate design jaipur", "ms gate jaipur", "iron gate manufacturer jaipur"],
  },
  {
    slug: "false-ceiling-ideas-small-flats-jaipur",
    title: "False Ceiling Ideas for Small Flats in Jaipur",
    excerpt: "False ceiling options for compact Jaipur apartments — what works, what to avoid, and how to make a small room feel larger.",
    category: "Interior Design",
    tags: ["false ceiling", "small flat", "jaipur", "interior tips"],
    publishedAt: "2026-03-26",
    readTime: "5 min read",
    metaTitle: "False Ceiling Ideas for Small Flats in Jaipur | Furnshin",
    metaDescription: "False ceiling design ideas for small Jaipur apartments. What works, what to avoid, and how to use ceiling design to make compact rooms feel larger.",
    keywords: ["false ceiling jaipur", "false ceiling small flat jaipur", "gypsum ceiling jaipur"],
  },
  {
    slug: "how-to-budget-home-interior-jaipur",
    title: "How to Budget Your Home Interior Project in Jaipur",
    excerpt: "A realistic, step-by-step guide to budgeting a home interior project — what costs what, what to expect, and how to avoid overspending.",
    category: "Interior Design",
    tags: ["interior budget", "jaipur", "home interior cost", "interior planning"],
    publishedAt: "2026-03-27",
    readTime: "7 min read",
    metaTitle: "How to Budget Your Home Interior Project in Jaipur | Furnshin",
    metaDescription: "A realistic guide to budgeting a home interior project in Jaipur. Room-wise cost breakdown and how to avoid the most common overspending mistakes.",
    keywords: ["interior budget jaipur", "home interior cost jaipur", "interior project cost jaipur"],
  },
  {
    slug: "interior-projects-across-jaipur-neighbourhoods",
    title: "Vaishali Nagar to Pratap Nagar: Interior Projects Across Jaipur",
    excerpt: "An overview of Furnshin's completed interior and furnishing projects across Jaipur's key residential neighbourhoods.",
    category: "Project Showcase",
    tags: ["jaipur interior", "vaishali nagar", "mansarovar", "pratap nagar"],
    publishedAt: "2026-03-28",
    readTime: "4 min read",
    metaTitle: "Interior Projects Across Jaipur Neighbourhoods | Furnshin",
    metaDescription: "Furnshin's interior and furnishing projects across Vaishali Nagar, Mansarovar, Pratap Nagar, Civil Lines, and Sanganer in Jaipur.",
    keywords: ["interior decorator jaipur", "home interior vaishali nagar jaipur", "interior designer mansarovar jaipur"],
  },
  {
    slug: "why-30-years-craftsmanship-matters-modern-interior",
    title: "Why 30 Years of Craftsmanship Still Matters in Modern Interior Design",
    excerpt: "In an age of fast furniture and digital-first brands, why experience and craft still produce better outcomes for homeowners.",
    category: "About Furnshin",
    tags: ["craftsmanship", "interior design", "jaipur", "furnshin"],
    publishedAt: "2026-03-29",
    readTime: "5 min read",
    metaTitle: "Why 30 Years of Craftsmanship Still Matters in Modern Interior Design | Furnshin",
    metaDescription: "Why experience and craft still matter in interior design. An honest perspective from Furnshin, founded in Jaipur in 1996.",
    keywords: ["craftsmanship interior jaipur", "experienced interior designer jaipur", "furnshin jaipur"],
  },
];
